# @package _global_

ha_teacher:
  chi: 0.3
  tau: 10
  epsilon: 1

  teacher_enable: true    # enable HA-Teacher or not
  teacher_correct: true    # whether HA-Teacher's actions are used for correcting HP-Student

  matlab_engine:
    stdout: false
    stderr: false
    working_path: "src/ha_teacher/matlab/"
    cvx_toolbox:
      setup: false
      relative_path: "./cvx"